version: '3.8'

services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build"

  php:
    image: php:8.2-fpm
    volumes:
      - ./backend:/var/www/backend

  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/backend
      - ./frontend/dist:/var/www/frontend
    depends_on:
      - php
      - frontend

